{{- if .Values.podDisruptionBudget.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "todo-app.fullname" . }}-audit-pdb
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit
spec:
  minAvailable: {{ .Values.podDisruptionBudget.audit.minAvailable }}
  selector:
    matchLabels:
      {{- include "todo-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: audit
{{- end }}
