apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-audit
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: audit
spec:
  type: {{ .Values.services.audit.type }}
  ports:
  - port: {{ .Values.services.audit.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: audit
