apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-frontend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.services.frontend.type }}
  ports:
  - port: {{ .Values.services.frontend.port }}
    targetPort: http
    protocol: TCP
    name: http
    {{- if eq .Values.services.frontend.type "NodePort" }}
    nodePort: {{ .Values.services.frontend.nodePort }}
    {{- end }}
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
