apiVersion: v1
kind: Service
metadata:
  name: {{ include "todo-app.fullname" . }}-notifications
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
spec:
  type: {{ .Values.services.notifications.type }}
  ports:
  - port: {{ .Values.services.notifications.port }}
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "todo-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: notifications
