apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
data:
  DATABASE_HOST: {{ .Values.config.databaseHost | quote }}
  DATABASE_PORT: {{ .Values.config.databasePort | quote }}
  DATABASE_NAME: {{ .Values.config.databaseName | quote }}
  TODO_API_URL: {{ .Values.config.todoApiUrl | quote }}
  CHATBOT_API_URL: {{ .Values.config.chatbotApiUrl | quote }}
  TODO_FRONTEND_PORT: {{ .Values.config.todoFrontendPort | quote }}
  CHATBOT_FRONTEND_PORT: {{ .Values.config.chatbotFrontendPort | quote }}
  ENVIRONMENT: {{ .Values.config.environment | quote }}
