apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: postgresql
spec:
  accessModes:
    - {{ .Values.storage.postgres.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.postgres.size }}
  storageClassName: {{ .Values.storage.postgres.storageClass }}
