apiVersion: v1
kind: Service
metadata:
  name: chatbot-backend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: chatbot-backend
spec:
  type: {{ .Values.services.chatbotBackend.type }}
  ports:
    - port: {{ .Values.services.chatbotBackend.port }}
      targetPort: {{ .Values.services.chatbotBackend.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: chatbot-backend
