apiVersion: v1
kind: Service
metadata:
  name: todo-backend
  labels:
    {{- include "todo-app.labels" . | nindent 4 }}
    app: todo-backend
spec:
  type: {{ .Values.services.todoBackend.type }}
  ports:
    - port: {{ .Values.services.todoBackend.port }}
      targetPort: {{ .Values.services.todoBackend.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: todo-backend
